name: mini aquila
solidity:
  import-remapping:
    - "@chainlink=https://github.com/smartcontractkit/chainlink"

dependencies:
  - name: Chainlink
    github: smartcontractkit/chainlink
    version:

dotenv: .env
networks:
  #default: ganache-local
  development:
    keyhash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    fee: 100000000000000000
    verify: False
  goerli-alchemy:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    vrf_coordinator: "0x2ca8e0c643bde4c2e08ab1fa0da3401adad7734d"
    link_address: "0x326c977e6efc84e512bb9c30f76e30c160ed06fb"
    keyhash: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    fee: 100000000000000000
    verify: False

wallets:
  from_key: ${PRIVATE_KEY}
